version: 2.1
orbs:
  gradle: circleci/gradle@3.0
executors:
  java17:
    docker:
      - image: 'eclipse-temurin:17-jdk-alpine'  

jobs:
  run-build:
    executor: java17
    steps:
    - run: apk add perl-utils
    - gradle/test:
        executor: java17
workflows:
  build:
    jobs:
      - run-build