version: 2.1
orbs:
  gradle: circleci/gradle@3.0
executors:
  java17:
    docker:
      - image: 'eclipse-temurin:17-jdk-alpine'  

jobs:
  install-shasum:
    executor: java17
    steps:
    - run: |
        apk add shasum
workflows:
  build:
    jobs:
      - install-shasum
      - gradle/test:
          executor: java17
