version: 2.1
  
executors:
  java17:
    docker:
      - image: 'eclipse-temurin:17-jdk-alpine'  

orbs:
  gradle: circleci/gradle@3.0

jobs:
  run-build:
    executor: java17
    steps:
    - run: apk add perl-utils
workflows:
  build:
    jobs:
      - run-build
      - gradle/test:
          requires: 
            - run-build
          executor: java17